name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm install
      - run: |
          npm run all
